language: java

env:
  global:
  - secure: KF4o6QO95xqTL1bwBOQQBP6bgJp7vaBRSZ4o8CrIK/8vSc6RAE+VGg4Q21UGjiyPJ+V3HR07qpOe9u/32ZtXIejTOg4UWjvOALw7IBczBF1xlUatVuKX3GGZOdSvnVaaNaxeM8rCJg80ixQ5/HZq+K8QiFCVYEkw0v6WEzJ7jMNb52e/Aptf7k2KvbZT+1loYXHMcqC37cm1SA3Ni4kdaBHkjs4YgOYnI3zCTwXDcZRYDNuqORS6VyMOA7sgiOyjMDhgYcgq6ypwHYj+JGpfKNrmdYAYFbHrBxzDdRWI9aKtRRN9/Al64/RpLjNucf3V+OaMI2zo9qMosdEsGe9posRnWA/Fsg1iiOYzGCZPTbziBkmFaF7AbB+Fyd0uXIJertVaB0hjEo7Mw72CGK75CZAbeorGtPG9Wk19GPWkj8L1BE1glB+FLwy5Qn6oCKaJsYhEp3mm+vBF/KHKIA1qGGTZH3HWYh9brOZgJYKrsBvwEcGQhtlPUd9yMVcbEw1sFLA77TffG+JgtTUQ062XjZEqOkpfOqoRUSq2KQU1eTismAkfwkFk1+bUgRaTYEyHlHsy9Tz7oRhYoGPtQ8r9TDPtmWuzQNzL6CGGxidaPOO1f+v6RTyQ0QLHhLvSXl2pTulNhM1ZlegcbXI9qPWjPg3MeNq/eaKWbrGiH+RzUGc=
  - secure: 2HAypCrcbLW8wCHNUqt1xYgGoZHSUWXy+YC5f6jjrMgNOUtJauGCvqjap/44/uGWtYVEGiLYqAmjUe4X7/pxxkq4mmkYGXdko4jIsGfhCqlhBt5PO32cp+1eHkk8rIIK/Upl9/pP/Via24zhmkpvi+Tfv2v427t0It6aW3Wv4k9EPF0/gMOgQvE3jpI1bwR5v6zvL89oLc16yzcUk0LaBuaT+08O58USB8ZKSLlsVhWec+ojyW6aN6/v1VjuW0Z4d6mIuJ8sBWfVWNyP5NH72S3bjLVyga+b/YUF+J7b/1TTCrnYe6Kr+qmPrsrgJCn0dlUNeEWuupBYkkM8S9+uJGfPLkPD4Ri9NwkM73+qnDWf8dUC+nXWVF57fxIsvwSsF5PsNC0Yhu9RP4EInEDNBNLYz8HwtbQ0ta39UYLP3RPsRlnMvgYZphrO0OQK1JBQmz0wDjgRPph3GcTaAic4KfmMViaq3xmE11gWmXh6aPZDWp3BsyQ0VRJ0K1ZdKAFqaMemarUhZUWIy7PeGxYi3IZQJg7zBS4aj5NiAV7AuIEszazTJ4EhrgA6jbkd0IO4/XEqaKaeJlM8sNoJ8sZj8HGEoJUtCYAbMg/DuE6aiYoxuJMdsJciXzIst+EgJu8DkNLW2F71U55IXmb2tJsAVZQjgP45u0SOCnO40vZ9pfs=
  - secure: NtV4sy9jMvlZYMuw4yQADgnxPM7Fgso9sNeO2xrpv/DQ8UQY7BVLIHwwkM6MVQ/6J1klU/BJ8inGwN8Z/0ygqI1Q5lBts/l1sOiYTPdCfx0aObpqg0FbPaSD3e1MW6SaX5Szy4MeMNefKkc56XI5+ywqi3kGxH0fNXqAjJDN+c+q+N9RQXN5VLVeYjJhxWKr3kTtKqJNwVnniWMTTkpolO7wvUuCOX6z06QU7iYkVCNzezaCXDdz+OLNlye/oXWx9Y7AEd/jkHVp78beTJ/qBeq+/LGNQD/5lA5A+y/Pjnc/9n3AusG3HuX/HNd9FdV/Wx34nY4QY8dsMEqYCEL1gwMJUgv0jn0eFbn/4qu/u8JpJ5OklOeMwqg5mhLT5sdWXoiw1GnoLsoADq22BUpbw37JBiN2jZFJOcylMfp22gsZMD1F8OJ7nzwjpI5JbnPpbaJ8J+K3I+P+uLvX95wDjPAy+znYxaFL9Jg9uzRPeJeLUz5daTxCLBGPvqDLVWSZ4Wo74c2Xm+Q7dtH/0cAUw6YWlb7Ogr6mnTuSTmk6h/5O9ZF5ZOOTl2s5ymi9PBmoBkhmt3fqlykh9NQVDjnOOHjflC66KIPQJvDEs19XOQeIm7MxGIk6DqSrDgKplx+OljicW/1MN2msfbtOrTD0DlMl2on66/XTbi+NHz4kLCY=

install: true

addons:
  sonarcloud:
    organization: "kentico-github"
    token:
      secure: "j2lyZTrsGvCSHJefMQLqKrQ5iicdUaJY0/7RLD2jMCpeXMhJa8fTvus3QPvjelw/uNeIUBAAPWrBjtkpgUDVlTxc+iz3+an6TvMBuabas81J7CSCEG7XBA27MHRCKtlmYa5hXL+FQcTDIYzNObM8722RPxuNT7Yx+Oq+GMNF2m2DCTzal4Fez7Ql2tDJIsxXmcfFQJeX0huBiEpCu/oDxf04IkleQE0Z56U+EnuGIvrffDkGYaCU/41WA5ZDfDqVBazE1fueaZs0yCPLLrAZX6Lm0uEykw0nvi6HjbOVTw2P0IKEsgKqJQn3m5K7f/nCprHB9kCjtFIyOPqv681OUvatXhbZ+/NE8BPxXhzZw0KIaDFIieQFdKd1KyxR3wFAIfNoLYZCRi0uUsxFIIgzrBrL5v9i2SvIPxaxxtwxsVQnEKHXLwJzbwhj6HIxWwI1WwaGXLB6+qCATTvacCRtDoZrG47/06haiVKWoLeO6epTEkb1GiEw0H84XFspZHVIGiUBrwTv6j0t4UPtXzipjQHofLpswAj+3KQbZ3NjfPlqcTI6KNgpiJMR3fBm141GihdNgVldMU42IG0kfbztlqGONVdU1udPQF/lNGHFuNStvJs1AWA1MM2wjT2ope6Q7l3l90ZcsmfiU1bjafE7RrU/rDX9+5FSId7Qj0/kS1c="

script:
  - ".travis/build.sh"

before_cache:
  # remove all the artifacts (JAR, ZIP) that are installed in local repo because of gradle deploy
  - rm -f  $HOME/.gradle/caches/modules-2/modules2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.sonar/cache
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper

before_install:
  - ".travis/unpack_deploy_keys.sh"

after_success:
  - ".travis/deploy_ghpages.sh"
