language: java

env:
  global:
  - secure: KF4o6QO95xqTL1bwBOQQBP6bgJp7vaBRSZ4o8CrIK/8vSc6RAE+VGg4Q21UGjiyPJ+V3HR07qpOe9u/32ZtXIejTOg4UWjvOALw7IBczBF1xlUatVuKX3GGZOdSvnVaaNaxeM8rCJg80ixQ5/HZq+K8QiFCVYEkw0v6WEzJ7jMNb52e/Aptf7k2KvbZT+1loYXHMcqC37cm1SA3Ni4kdaBHkjs4YgOYnI3zCTwXDcZRYDNuqORS6VyMOA7sgiOyjMDhgYcgq6ypwHYj+JGpfKNrmdYAYFbHrBxzDdRWI9aKtRRN9/Al64/RpLjNucf3V+OaMI2zo9qMosdEsGe9posRnWA/Fsg1iiOYzGCZPTbziBkmFaF7AbB+Fyd0uXIJertVaB0hjEo7Mw72CGK75CZAbeorGtPG9Wk19GPWkj8L1BE1glB+FLwy5Qn6oCKaJsYhEp3mm+vBF/KHKIA1qGGTZH3HWYh9brOZgJYKrsBvwEcGQhtlPUd9yMVcbEw1sFLA77TffG+JgtTUQ062XjZEqOkpfOqoRUSq2KQU1eTismAkfwkFk1+bUgRaTYEyHlHsy9Tz7oRhYoGPtQ8r9TDPtmWuzQNzL6CGGxidaPOO1f+v6RTyQ0QLHhLvSXl2pTulNhM1ZlegcbXI9qPWjPg3MeNq/eaKWbrGiH+RzUGc=
  - secure: 2HAypCrcbLW8wCHNUqt1xYgGoZHSUWXy+YC5f6jjrMgNOUtJauGCvqjap/44/uGWtYVEGiLYqAmjUe4X7/pxxkq4mmkYGXdko4jIsGfhCqlhBt5PO32cp+1eHkk8rIIK/Upl9/pP/Via24zhmkpvi+Tfv2v427t0It6aW3Wv4k9EPF0/gMOgQvE3jpI1bwR5v6zvL89oLc16yzcUk0LaBuaT+08O58USB8ZKSLlsVhWec+ojyW6aN6/v1VjuW0Z4d6mIuJ8sBWfVWNyP5NH72S3bjLVyga+b/YUF+J7b/1TTCrnYe6Kr+qmPrsrgJCn0dlUNeEWuupBYkkM8S9+uJGfPLkPD4Ri9NwkM73+qnDWf8dUC+nXWVF57fxIsvwSsF5PsNC0Yhu9RP4EInEDNBNLYz8HwtbQ0ta39UYLP3RPsRlnMvgYZphrO0OQK1JBQmz0wDjgRPph3GcTaAic4KfmMViaq3xmE11gWmXh6aPZDWp3BsyQ0VRJ0K1ZdKAFqaMemarUhZUWIy7PeGxYi3IZQJg7zBS4aj5NiAV7AuIEszazTJ4EhrgA6jbkd0IO4/XEqaKaeJlM8sNoJ8sZj8HGEoJUtCYAbMg/DuE6aiYoxuJMdsJciXzIst+EgJu8DkNLW2F71U55IXmb2tJsAVZQjgP45u0SOCnO40vZ9pfs=
  - secure: l/AqEJKmzpneu67z/zZHbluCv2m7DjMgJnLBvh3H0SUHUbESMnrasKxT3q3IXp/S6tlwSnsUU3zOKc7sQtFh4RUTdu98fv1dcc01B3VGyzzor03J1xaW123foBeY39iroBy6xyAAGbcujJCnH0LZ0Sinq2JSbZ2BtE440tPbKFNHUxLScJViIod7uxoWHLLCQhf9K830reBWdvQFsFkQrCoLTzg3gPHXoeSnVLCfcMWEjLzoI4lVAgtvuk2naeenntdyObIx9YduyUdEb/Wk1BpFGGeYOP7h+Dq4WSHUp45R/1skzJWeN8HHSnP3QWVWATanVhjYUVRX/tMk6yC4BgjdfXwCRWc/2ZAS9ovhfccmMi1V2lJR+xEtxPyAf5zSzk2ybgIZ9Hq9J1544w3rgo3D5gY+nbl2lnAGO3JG8UXHudfh9NmWMH/nrtTST4CXM7Gh8UVp8GNOtlSQfrzPgCSOqSFIuaXE9SV2Dju+2qDTDKctv5G1iJqTvpQlt6XH6YzuYNxw5DJ7uC0/i1wh5HULCtHlNOXayo7/LCHYwlLtFnIEhafX0eS+cRsln+GS8Gri82Vk3F+BY++vdWNYEwRVAa1jj7KWufsd0Q7fSq3avu20+mw6/GD7tI0lWl9RYUu3obITNrqHY/8a8QF6QTEmk4koSetClfdGXZuonOc=

install: true

addons:
  sonarcloud:
    organization: "kentico-github"
    token:
      secure: "j2lyZTrsGvCSHJefMQLqKrQ5iicdUaJY0/7RLD2jMCpeXMhJa8fTvus3QPvjelw/uNeIUBAAPWrBjtkpgUDVlTxc+iz3+an6TvMBuabas81J7CSCEG7XBA27MHRCKtlmYa5hXL+FQcTDIYzNObM8722RPxuNT7Yx+Oq+GMNF2m2DCTzal4Fez7Ql2tDJIsxXmcfFQJeX0huBiEpCu/oDxf04IkleQE0Z56U+EnuGIvrffDkGYaCU/41WA5ZDfDqVBazE1fueaZs0yCPLLrAZX6Lm0uEykw0nvi6HjbOVTw2P0IKEsgKqJQn3m5K7f/nCprHB9kCjtFIyOPqv681OUvatXhbZ+/NE8BPxXhzZw0KIaDFIieQFdKd1KyxR3wFAIfNoLYZCRi0uUsxFIIgzrBrL5v9i2SvIPxaxxtwxsVQnEKHXLwJzbwhj6HIxWwI1WwaGXLB6+qCATTvacCRtDoZrG47/06haiVKWoLeO6epTEkb1GiEw0H84XFspZHVIGiUBrwTv6j0t4UPtXzipjQHofLpswAj+3KQbZ3NjfPlqcTI6KNgpiJMR3fBm141GihdNgVldMU42IG0kfbztlqGONVdU1udPQF/lNGHFuNStvJs1AWA1MM2wjT2ope6Q7l3l90ZcsmfiU1bjafE7RrU/rDX9+5FSId7Qj0/kS1c="

script:
  - ".travis/build.sh"

before_cache:
  # remove all the artifacts (JAR, ZIP) that are installed in local repo because of gradle deploy
  - rm -f  $HOME/.gradle/caches/modules-2/modules2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.sonar/cache
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper

before_install:
  - ".travis/unpack_deploy_keys.sh"

after_success:
  - ".travis/deploy_ghpages.sh"
